<a href="https://colab.research.google.com/github/hemahari2419/230282601037Hema/blob/MultipleLinearRegression37/Multiple_Linear_RegressionRRN37.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv("/content/sample_data/Student_Performance.csv")
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
dataset

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values
X, y

(array([[7, 99, 'Yes', 9, 1],
        [4, 82, 'No', 4, 2],
        [8, 51, 'Yes', 7, 2],
        ...,
        [6, 83, 'Yes', 8, 5],
        [9, 97, 'Yes', 7, 0],
        [7, 74, 'No', 8, 1]], dtype=object),
 array([1, 2, 2, ..., 5, 0, 1]))

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
integer_column_index = 4
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [integer_column_index])],
    remainder='passthrough'
)
X_encoded = ct.fit_transform(dataset)
feature_names = ct.get_feature_names_out(input_features=dataset.columns)
encoded_df = pd.DataFrame(X_encoded, columns=feature_names)
print(encoded_df)


     encoder__Sample Question Papers Practiced_0  \
0                                            0.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
9995                                         0.0   
9996                                         0.0   
9997                                         0.0   
9998                                         1.0   
9999                                         0.0   

     encoder__Sample Question Papers Practiced_1  \
0                                            1.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
9995       

In [10]:
X = X[:, 1:]
dataset

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)
X_train, y_train

(array([['No', 6, 4],
        ['No', 7, 4],
        ['Yes', 8, 1],
        ...,
        ['Yes', 6, 5],
        ['No', 4, 8],
        ['Yes', 8, 1]], dtype=object),
 array([4, 4, 1, ..., 5, 8, 1]))

In [12]:
X_test, y_test

(array([['No', 9, 3],
        ['No', 4, 7],
        ['No', 5, 6],
        ...,
        ['Yes', 7, 7],
        ['No', 8, 5],
        ['No', 5, 1]], dtype=object),
 array([3, 7, 6, ..., 7, 5, 1]))

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
categorical_features = dataset.select_dtypes(include=['object']).columns.tolist()
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', dataset.select_dtypes(exclude=['object']).columns),

        ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), categorical_features)

    ])
X_processed = preprocessor.fit_transform(dataset)
feature_names = preprocessor.get_feature_names_out(dataset.columns)
encoded_df = pd.DataFrame(X_processed, columns=feature_names)
X = encoded_df
y = dataset['Performance Index']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)




In [21]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred

array([53., 50., 80., ..., 66., 27., 21.])

In [22]:
accuracy = regressor.score(X_test,y_test)
print('Accuracy of the model is',accuracy*100,'%')

Accuracy of the model is 100.0 %


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)
accuracy = regressor.score(X_test,y_test)
print('Accuracy of the model is',accuracy*100,'%')

Accuracy of the model is 100.0 %
